# Setup
title:               'Data Science blog for the IFT-16758 class'
tagline:             'tagline'
description:         'Blog description'
url:                 https://julien-hebert-doutreloux.github.io/Project-Blog-IFT6758-A23/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              MJHD
  url:               https://github.com/julien-hebert-doutreloux/
  email:             jhd@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
